'use strict';

/**
 * @param {{ target: string, requirement: string, codeText?: string, language?: string, dryRun?: boolean }} opts
 * @returns {Promise<{ summary: string, patchPlan: Array<Record<string, unknown>>, patch: string, notes: string[], targetPath: string, language: string }>}
 */
async function patchFirmware(opts) {
  const target = String(opts.target || 'src/main.c');
  const req = String(opts.requirement || '').trim();
  const lang = String(opts.language || 'arduino').trim() || 'arduino';
  const code = String(opts.codeText || '').trim();
  const hasLoop = /\bvoid\s+loop\s*\(/.test(code);
  const hasSetup = /\bvoid\s+setup\s*\(/.test(code);
  /** @type {Array<Record<string, unknown>>} */
  const patchPlan = [];
  if (hasSetup) {
    patchPlan.push({
      op: 'insert',
      target: 'setup()',
      description: '在 setup 中补充新增功能初始化与日志配置'
    });
  }
  if (hasLoop) {
    patchPlan.push({
      op: 'replace',
      target: 'loop()',
      description: '在 loop 中加入基于需求的状态控制逻辑'
    });
  } else {
    patchPlan.push({
      op: 'insert',
      target: 'main loop',
      description: '新增主循环逻辑骨架并挂接功能分支'
    });
  }
  patchPlan.push({
    op: 'insert',
    target: 'helpers',
    description: '新增辅助函数（阈值判定/日志函数）'
  });

  const patch = [
    `--- a/${target}`,
    `+++ b/${target}`,
    '@@',
    '- // TODO',
    `+ // TODO: ${req || 'add feature'}`,
    '+ // generated by cli firmware:patch (dry-run plan)',
    hasLoop ? '+ // integrate logic into loop()' : '+ // create loop() skeleton'
  ].join('\n');
  return {
    summary: '已生成固件代码补丁建议（CLI dry-run）',
    patchPlan,
    patch,
    notes: ['当前为 CLI dry-run 计划，不直接写文件；建议由 skill 或人工复核后应用。'],
    targetPath: target,
    language: lang
  };
}

module.exports = {
  patchFirmware
};
